/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Modelo.CalculadoraDiagonal calculadora = new Modelo.CalculadoraDiagonal();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnMostrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnMostrar.setText("Multiplicar en diagonal");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
      try {
        int[] lista1 = new int[5];
        int[] lista2 = new int[5];

        // Ingresar lista 1 (5 números)
        for (int i = 0; i < 5; i++) {
            String input = JOptionPane.showInputDialog(this, 
                "Ingrese el número " + (i + 1) + " para la Lista 1:");
            if (input == null) {
                txtResultado.setText("Operación cancelada.");
                return;
            }
            lista1[i] = Integer.parseInt(input.trim());
        }

        // Ingresar lista 2 (5 números)
        for (int i = 0; i < 5; i++) {
            String input = JOptionPane.showInputDialog(this, 
                "Ingrese el número " + (i + 1) + " para la Lista 2:");
            if (input == null) {
                txtResultado.setText("Operación cancelada.");
                return;
            }
            lista2[i] = Integer.parseInt(input.trim());
        }

        // Mostrar listas
        StringBuilder salida = new StringBuilder();
        salida.append("Lista 1: ").append(arrayToString(lista1)).append("\n");
        salida.append("Lista 2: ").append(arrayToString(lista2)).append("\n");
        salida.append("\nMultiplicación en diagonal:\n");
        salida.append("----------------------------\n");

        // Multiplicar en diagonal
        for (int i = 0; i < 5; i++) {
            int num1 = lista1[i];
            int num2 = lista2[4 - i]; // 4, 3, 2, 1, 0 → inverso de lista2
            int producto = num1 * num2;

            boolean esPrimo = calculadora.esPrimo(producto);
            boolean esMultiploDeDos = calculadora.esMultiploDeDos(producto);

            salida.append(num1)
                  .append(" × ")
                  .append(num2)
                  .append(" = ")
                  .append(producto)
                  .append("  Primo: ")
                  .append(esPrimo ? "Sí" : "No")
                  .append(", Múltiplo de 2: ")
                  .append(esMultiploDeDos ? "Sí" : "No")
                  .append("\n");
        }

        txtResultado.setText(salida.toString());

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Error: Debe ingresar números enteros válidos.",
            "Entrada inválida",
            JOptionPane.ERROR_MESSAGE);
        txtResultado.setText("Error en la entrada de datos.");
    }
    }//GEN-LAST:event_btnMostrarActionPerformed
// Convierte un arreglo a String tipo [1, 2, 3]
private String arrayToString(int[] arr) {
    StringBuilder sb = new StringBuilder();
    sb.append("[");
    for (int i = 0; i < arr.length; i++) {
        sb.append(arr[i]);
        if (i < arr.length - 1) sb.append(", ");
    }
    sb.append("]");
    return sb.toString();
}
    
 

   
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
