/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import BDD.ConexionBDD;
import Controlador.UsuarioControlador;
import Modelo.UsuarioModelo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;




/**
 *
 * @author Usuario
 */
public class VistaUsuario extends javax.swing.JFrame {
    //variable para el controlador 
    private UsuarioControlador controlador;


    /**
     * Creates new form VistaJComboBox
     */
    public VistaUsuario() {
        initComponents();
        controlador = new UsuarioControlador();
        cargarRolesEnComboBox();
        this.setLocationRelativeTo(null);
        
        //CODIGO JSPLITPANE
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setResizeWeight(0.4);
        jSplitPane1.setOneTouchExpandable(true);
        
        // Cargar la tabla al iniciar la ventana
        cargarTablaUsuarios();
        
        // JSlider interactivo - muestra el valor en tiempo real
              
        sliderNivel.addChangeListener(e -> {
            int valor = sliderNivel.getValue();
            
            if (valor == 100) {
                lblNivelActual.setText("Acceso permitido");
                lblNivelActual.setForeground(new java.awt.Color(0, 153, 0)); // Verde oscuro
            } else {
                lblNivelActual.setText("Acceso denegado (necesitas nivel 100)");
                lblNivelActual.setForeground(new java.awt.Color(204, 0, 0)); // Rojo
            }
        });
        
        
        
        
        
        // Botón para iniciar animación automática del slider hasta 100
        btnAnimar.addActionListener(e -> {
            new Thread(() -> {
                int valorInicial = sliderNivel.getValue();
                for (int i = valorInicial; i <= 100; i++) {
                    final int valor = i;
                    java.awt.EventQueue.invokeLater(() -> {
                        sliderNivel.setValue(valor);
                        // El ChangeListener ya actualiza el texto y la barra automáticamente
                    });
                    try {
                        Thread.sleep(50); // Velocidad de la animación (50ms = suave y rápido)
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            }).start();
        });
       
    }
    
    private void cargarRolesEnComboBox(){
        ComboRol.addItem("Administrador");
        ComboRol.addItem("Usuario");
    }
     private void cargarTablaUsuarios() {
        // Modelo de la tabla (no editable)
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // La tabla no se puede editar directamente
            }
        };
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Rol");

        try {
            ConexionBDD conexionBDD = new ConexionBDD();
            Connection conexion = conexionBDD.conectar();
            
            String sql = "SELECT idUsuario, nombre, rol FROM usuarios ORDER BY idUsuario";
            PreparedStatement pstmt = conexion.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("idUsuario"),
                    rs.getString("nombre"),
                    rs.getString("rol")
                };
                modelo.addRow(fila);
            }
            
            rs.close();
            pstmt.close();
            conexion.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        }
        
        TablaUsuarios.setModel(modelo);
        
        // Opcional: ajustar ancho de columnas para que quede bonito
        TablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        TablaUsuarios.getColumnModel().getColumn(1).setPreferredWidth(200); // Nombre
        TablaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150); // Rol
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PanelDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        ComboRol = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        sliderNivel = new javax.swing.JSlider();
        lblTituloSlider = new javax.swing.JLabel();
        lblNivelActual = new javax.swing.JLabel();
        btnAnimar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelDatos.setBackground(new java.awt.Color(153, 153, 153));
        PanelDatos.setForeground(new java.awt.Color(51, 255, 255));

        lblNombre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 102, 102));
        lblNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblRol.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblRol.setForeground(new java.awt.Color(0, 102, 102));
        lblRol.setText("Elegir Rol");

        ComboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRolActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 102, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRol)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnGuardar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRol)
                .addGap(18, 18, 18)
                .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnGuardar)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(PanelDatos);

        PanelTabla.setBackground(new java.awt.Color(255, 204, 204));
        PanelTabla.setForeground(new java.awt.Color(255, 204, 204));
        PanelTabla.setLayout(new java.awt.BorderLayout());

        TablaUsuarios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TablaUsuarios.setForeground(new java.awt.Color(0, 102, 102));
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Rol"
            }
        ));
        jScrollPane1.setViewportView(TablaUsuarios);

        PanelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(PanelTabla);
        PanelTabla.getAccessibleContext().setAccessibleDescription("");

        sliderNivel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        sliderNivel.setForeground(new java.awt.Color(0, 102, 102));
        sliderNivel.setValue(0);

        lblTituloSlider.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTituloSlider.setForeground(new java.awt.Color(0, 102, 102));
        lblTituloSlider.setText("Nivel de acceso");

        lblNivelActual.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNivelActual.setForeground(new java.awt.Color(0, 102, 102));
        lblNivelActual.setText("Nivel Actual: 0");

        btnAnimar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAnimar.setForeground(new java.awt.Color(0, 102, 102));
        btnAnimar.setText("Iniciar su acceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSplitPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnAnimar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloSlider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNivelActual)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            UsuarioModelo usuario = new UsuarioModelo();
            usuario.setNombre(txtNombre.getText());
            usuario.setRol((String) ComboRol.getSelectedItem() );

            boolean guardado = controlador.guardarUsuario(usuario);

            if(guardado){
                JOptionPane.showMessageDialog(this, "Usuario guardado");
                txtNombre.setText("");
                // ¡Actualizar la tabla automáticamente!
                cargarTablaUsuarios();
            }else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ComboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRolActionPerformed
        // TODO add your handling code here:
        String rolSeleccionado = (String) ComboRol.getSelectedItem();
        System.out.println("Rol seleccionado: " + rolSeleccionado);
    }//GEN-LAST:event_ComboRolActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        ComboRol.requestFocus();

    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboRol;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelTabla;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnAnimar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblNivelActual;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTituloSlider;
    private javax.swing.JSlider sliderNivel;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
